### ISSUE TITLE
Funktioniert nicht

### ISSUE THREAD

**Issue by lhalbritter-tu** [maxganguly/JavaWebserver#1]
Hilfe deine App geht nicht. Bitte fix.

- [x] Fix it
- [x] issue gschriebn

**Comment by maxganguly** [comment]
Was funktioniert nicht?

**Comment by lhalbritter-tu** [comment]
Nein ist kaputt deine App. Bitte reparier. 👎

**Comment by maxganguly** [comment]
> Nein ist kaputt deine App. Bitte reparier. 👎

**Was funktioniert nicht und was funktioniert?**

**Comment by lhalbritter-tu** [comment]
> > Nein ist kaputt deine App. Bitte reparier. 👎
> 
> **Was funktioniert nicht und was funktioniert?**

Wieso verstehen Sie  mich nicht? Es geht nicht. Ich habe diese Fehlermeldung erhalten:

`QW1vbmcgVXM=`

Bitte helfe mir!

**Comment by maxganguly** [comment]
Was haben Sie gemacht bevor Sie diese Fehlermeldung erhalten haben?

**Comment by lhalbritter-tu** [comment]
Hmm, wenn ich mich recht erinnere habe ich davor ein vorzügliches Steak verspeist 😋 Aber bitte helfen Sie mir jetzt!

**Comment by maxganguly** [comment]
Welchen Befehl haben Sie ausgeführt das diese Fehlermeldung entstanden ist?

**Comment by lhalbritter-tu** [comment]
Glaub das war `sudo shutdown -h now` oder `shutdown /s`, probieren Sie beides mal im terminal.

**Comment by maxganguly** [comment]
Warum verwenden Sie nicht die Befehle welche in dem [ReadMe.md ](https://raw.githubusercontent.com/maxganguly/JavaWebserver/main/ReadMe.md)  angegeben sind?

**Comment by lhalbritter-tu** [comment]
Ich habe aber keine 1.7+ Ameisen in meinem Computer 😔

**Comment by lhalbritter-tu** [comment]
Ich bitte um Zusendung von 1.7+ Ameisen. Ich kann auch den Versand zahlen.

**Comment by maxganguly** [comment]
Das Readme wurde geändert, besteht das Problem weiterhin?

**Comment by lhalbritter-tu** [comment]
Nein ich kann nix clonen. Der Name ist falsch im ReadMe 😠

**Comment by maxganguly** [comment]
Der Name wurde korrigiert

**Comment by lhalbritter-tu** [comment]
Okay danke, ich weiß jetzt was der Problem war: Das Steak war nicht vegan. Danke für die Hilfe Programmiermensch.
